dataset: CIFAR10
weight_init: kaiming_normal
model: Conv4
align_loss: se
weight_align_factor: 1
data_transform: True
num_clients: 20
bias: True
local_epochs: 5
dataset_split: iid
batch_size: 32
merge_iter: 100
