dataset: CIFAR10
weight_init: kaiming_normal
model: Conv4

align_loss: ae

weight_align_factor: 1
data_transform: True
num_clients: 3
bias: True
local_epochs: 5
dataset_split: disjoint_classes
#dirichlet_alpha: 0.3
batch_size: 50
merge_iter: 1500
