dataset: CIFAR10
weight_init: kaiming_normal
model: LeNetCifar10
align_loss: ae
weight_align_factor: 3
data_transform: True
num_clients: 100
bias: True
local_epochs: 15
dataset_split: dirichlet
dirichlet_alpha: 0.3
batch_size: 32

