dataset: CIFAR10
weight_init: default
model: LeNetCifar10
align_loss: se
weight_align_factor: 3
data_transform: True
num_clients: 20
bias: True
local_epochs: 5
dataset_split: dirichlet
dirichlet_alpha: 0.3
batch_size: 32
merge_iter: 300
