dataset: CIFAR100
weight_init: kaiming_normal
model: Conv4
align_loss: se
weight_align_factor: 1
data_transform: True
num_clients: 10
bias: True
local_epochs: 5
dataset_split: iid
dirichlet_alpha: 0.3
batch_size: 50
merge_iter: 500
same_initialization: False
random_topology: True