dataset: CIFAR10
weight_init: kaiming_normal
model: LeNetCifar10
align_loss: se
weight_align_factor: 1
data_transform: True
num_clients: 100
bias: True
local_epochs: 1
dataset_split: iid
batch_size: 8

