dataset: CIFAR10
weight_init: kaiming_normal
#kaiming_normal
model: Conv4
#VGG11
align_loss: ae
weight_align_factor: 1
data_transform: True
num_clients: 16
#16
bias: True
local_epochs: 5
dataset_split: iid
#dirichlet
dirichlet_alpha: 0.5
batch_size: 50
merge_iter: 500
