dataset: Fashion_MNIST
weight_init: kaiming_normal
model: MLP

align_loss: se

weight_align_factor: 1
data_transform: True
num_clients: 10
bias: True
local_epochs: 1
dataset_split: dirichlet
dirichlet_alpha: 0.3
batch_size: 50
merge_iter: 300
