dataset: MNIST
weight_init: kaiming_normal
model: MLP
align_loss: ae
weight_align_factor: 1
data_transform: True
num_clients: 3
bias: True
local_epochs: 1
dataset_split: iid
dirichlet_alpha: 0.6
batch_size: 50
merge_iter: 3

single_model: True