dataset: CIFAR10
weight_init: kaiming_normal
model: Conv4
align_loss: ae
weight_align_factor: 1
data_transform: True
num_clients: 10
bias: True
local_epochs: 5
dataset_split: dirichlet
dirichlet_alpha: 0.6
batch_size: 50
merge_iter: 2500
same_initialization: False
random_topology: True